PortalSearch/urls.py
from os import stat
from django import urls
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls')),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name= "reset_password.html"), name= "reset_password" ),
   path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_sent.html"), name = "password_reset_done"),
   path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"), name = 'password_reset_confirm'),
   path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name= "reset_password_complete.html"), name= 'password_reset_complete'),

]
#Url patterns here
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

projects/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('', views.projects, name ='projects'),
    path('project/<str:pk>/', views.project, name='project'),
    path('create-project/', views.createProject, name = 'create-project'),
    path('update-project/<str:pk>/', views.updateProject, name= 'update-project'),
    path('delete-project/<str:pk>/', views.deleteProject, name= 'delete-project')
]

users/urls.py
from django.urls import path
from .import views
import users

urlpatterns=[
 path('login/', views.loginPage, name='login'),
 path('logout/', views.logoutUser, name = 'logout'),
  path('register/', views.registerUser, name = 'register'),
 path('', views.profiles, name='profiles'),
 path('profile/<str:pk>/', views.userProfile, name= 'user-profile'),
 path('account/', views.userAccount, name= 'account'),
 path('edit-account/', views.editAccount, name='edit-account'),
 path('create-projects/', views.createCurrentProject, name = 'create-projects'),
 path('update-projects/<str:pk>/', views.updateCurrentProject, name= 'update-projects'),
 path('delete-projects/<str:pk>/', views.deleteCurrentProject, name= 'delete-projects'),
 path('inbox/', views.inbox, name='inbox'),
 path('message/<str:pk>/', views.viewMessage, name='message'),
 path('create-message/<str:pk>/', views.createMessage, name='create-message')
]

projects/models.py
from typing import cast
from django.contrib.admin.options import BaseModelAdmin
from django.db import models
import uuid
from users.models import Profile
from django.db.models.deletion import CASCADE
# Create your models here.
class Project(models.Model):
 owner =models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL )

 title = models.CharField(max_length=200)
 description = models.TextField(null=True, blank=True)
 source_link = models.CharField(max_length=2000, null=True, blank=True)
 featured_image = models.ImageField(null=True, blank =True, default = 'default.jpg')
 created = models.DateField(auto_now_add=True)
 id=models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
 def __str__(self):
  return self.title

class Review(models.Model):
 owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True) 
 project = models.ForeignKey(Project, on_delete=CASCADE)
 body = models.TextField(null=True, blank=True)
 created = models.DateTimeField(auto_now_add=True)
 id= models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

 def __str__(self):
  return self.body
 class Meta:
   ordering =['-created']

projects/forms.py
from django import forms
from django.db import models
from django.db.models import fields
from django.forms import ModelForm
from .models import Project, Review
from django.forms import forms


class ProjectForm(ModelForm):
 class Meta:
  model = Project
  fields = '__all__'

 def __init__(self, *args, **kwargs):
  super(ProjectForm, self).__init__(*args, **kwargs)
  for name, field in self.fields.items():
   field.widget.attrs.update({'class': 'input'})

class ReviewForm(ModelForm):
 class Meta:
  model =Review
  fields =['body']
  labels= {
   'body': 'Add your comments'
  }
 def __init__(self, *args, **kwargs):
  super(ReviewForm, self).__init__(*args, **kwargs)
  for name, field in self.fields.items():
   field.widget.attrs.update({'class': 'input'}) 

projects/views.py
from django.core import paginator
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Project
from .forms import ProjectForm, ReviewForm
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from .utils import searchProjects, paginateProjects
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib import messages
# Create your views here.


def projects(request):
  projects, search_query= searchProjects(request)
  custom_range, projects = paginateProjects(request,projects, 3)
  context ={'projects':projects, 'search_query':search_query, 'custom_range': custom_range}
  return render(request, 'projects/projects.html', context)

def project(request, pk):
    projObj = Project.objects.get(id=pk)
    form = ReviewForm()
    if request.method =='POST':
      form = ReviewForm(request.POST)
      review = form.save(commit=False)
      review.project = projObj
      review.owner = request.user.profile
      review.save()
      messages.success(request,"Your Review was Successfully Posted")  
      return redirect('project', pk=projObj.id)

    print('projObj', projObj)
    return render(request, 'projects/single-project.html', {'project':projObj, 'form':form})

@login_required(login_url="login")
def createProject(request):
 profile = request.user.profile
 form = ProjectForm()
 if request.method =='POST':
  form = ProjectForm(request.POST, request.FILES)
  if form.is_valid():
   project =form.save(commit=False)
   project.owner =profile
   project.save()
   return redirect('projects')

 context ={'form':form}
 return render(request, 'projects/project_form.html', context)

@login_required(login_url="login")
def updateProject(request, pk):
 profile = request.user.profile 
 project = profile.project_set.get(id=pk)
 form = ProjectForm(instance =project)
 if request.method =='POST':
  form = ProjectForm(request.POST,request.FILES, instance =project)
  if form.is_valid():
   form.save()
   return redirect('projects')

 context ={'form':form}
 return render(request, 'projects/project_form.html', context) 

@login_required(login_url="login")
def deleteProject(request, pk):
 profile = request.user.profile 
 project = profile.project_set.get(id=pk)
 context = {'object':project}
 if request.method =='POST':
  project.delete()
  return redirect('projects')

 return render(request, 'projects/delete_template.html', context)

projects/templates/projects/delete_template.html
{%extends 'main.html'%} {%block content%}
<form method="POST">
  {%csrf_token%}
  <p>Are you sure you want to delete "{{object}}"?</p>
  <a href="{% url 'projects' %}">Go Back</a>
  <input type="submit" value="confirm" />
</form>
{%endblock content%}

projects/templates/projects/project_form.html
{%extends 'main.html'%} {%block content%}

<!-- Main Section -->
<main class="formPage my-xl">
  <div class="content-box">
    <div class="formWrapper">
      <a class="backButton" href="{%url 'projects'%}"
        ><i class="im im-angle-left"></i
      ></a>
      <br />

      <form class="form" method="POST" enctype="multipart/form-data">
        {% csrf_token %} {%for field in form%}
        <!-- Input:Text -->
        <div class="form__field">
          <label for="formInput#text">{{field.label}} </label>
          {{field}}
        </div>
        {%endfor%}

        <input
          class="btn btn--sub btn--lg my-md"
          type="submit"
          value="Submit"
        />
      </form>
    </div>
  </div>
</main>
{%endblock content%}

projects/templates/projects/projects.html
{% extends 'main.html' %} {%block content%}

<!-- Main Section -->
<main class="projects">
  <section class="hero-section text-center">
    <div class="container container--narrow">
      <div class="hero-section__box">
        <h2>Search for <span>Projects</span></h2>
      </div>

      <div class="hero-section__search">
        <form
          id="searchForm"
          class="form"
          action="{%url 'projects'%}"
          method="get"
        >
          <div class="form__field">
            <label for="formInput#search">Search By Projects </label>
            <input
              class="input input--text"
              id="formInput#search"
              type="text"
              name="search_query"
              value="{{search_query}}"
              placeholder="Search by Project Title"
            />
          </div>

          <input class="btn btn--sub btn--lg" type="submit" value="Search" />
        </form>
      </div>
    </div>
  </section>
  <!-- Search Result: DevList -->
  <section class="projectsList">
    <div class="container">
      <div class="grid grid--three">
        {%for project in projects%}
        <div class="column">
          <div class="card project">
            <a href="{%url 'project' project.id%}" class="project">
              <img
                class="project__thumbnail"
                src="{{project.featured_image.url}}"
                alt="project thumbnail"
              />
              <div class="card__body">
                <h3 class="project__title">{{project.title}}</h3>
                <p>
                  <a
                    class="project_author"
                    href="{%url 'user-profile' project.owner.id%}"
                    >{{project.owner.name}}</a
                  >
                </p>
              </div>
            </a>
          </div>
        </div>
        {%endfor%}
      </div>
    </div>
  </section>
  {%include 'pagination.html' with queryset=projects custom_range=custom_range%}
</main>

{% endblock content %}

projects/templates/projects/single-project.html
{%extends 'main.html'%} {%block content%}


<!-- Main Section -->
  <main class="singleProject my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          {%if project.source_link%}
          <a class="singleProject__liveLink" href="#" target="_blank"><i class="im im-external-link"></i>Source Code
          </a>
          {%endif%}
        </div>
        <div class="column column--2of3">
          <img class="singleProject__preview" src="{{project.featured_image.url}}" alt="portfolio thumbnail" />
          <a href="{%url 'user-profile' project.owner.id%}" class="singleProject__developer">{{project.owner.name}}</a>
          <h2 class="singleProject__title">{{project.title}}</h2>
          <h3 class="singleProject__subtitle">About the Project</h3>
          <div class="singleProject__info">
            {{project.description}}
          </div>

          <div class="comments">
            <h3 class="singleProject__subtitle">Feedback</h3>
           {%if request.user.is_authenticated%}

            <form class="form" action="{%url 'project' project.id%}" method="POST">
              {%csrf_token%}
              {%for field in form%}
              <!-- Textarea -->
              <div class="form__field">
                <label for="formInput#textarea">{{field.label}}</label>
                {{field}}
                
              </div>
              {%endfor%}
              <input class="btn btn--sub btn--lg" type="submit" value="Comments" />
            </form>
            {%else%}
            <a href ="{%url 'login'%}?next={{request.path}}">Please Login to leave a review</a>
            {%endif%}
            <div class="commentList">
              {%for review in project.review_set.all%}
              {%if review.body%}
              <div class="comment">
                <a href="{%url 'user-profile' review.owner.id%}">
                  <img class="avatar avatar--md"
                    src="{{review.owner.profile_image.url}}" alt="user" />
                </a>
                <div class="comment__details">
                  <a href="{%url 'user-profile' review.owner.id%}" class="comment__author">{{review.owner.name}}</a>
                  <p class="comment__info">
                    {{review.body|linebreaksbr}}</p>
                </div>
              </div>
              {%endif%}
              {%endfor%}
              <div class="comment">
                <a href="profile.html">
                 
                
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
  </main>
{%endblock content%}